
port: 5002

# this line below hides the banner on the homepage. Github pages always overrides this to 'true' so we can tell
# when we are deploying the site there vs a local machine
safe: false

google-analytics-ua: UA-67501679-17
timezone: America/New_York

url: https://www.covideducationrecovery.global
baseurl: /

# Site settings
title: COVID-19 Global Education Recovery Tracker 
email: help@covideducationrecovery.global
description: "Monitoring the impact of the COVID-19 pandemic on response and recovery for students across the globe."
image: img/og-image.png

# Build settings
markdown: kramdown
permalink: pretty